apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak-unibl
  namespace: ${NAMESPACE}
spec:
  instances: ${KEYCLOAK_INSTANCES}

  bootstrapAdmin:
    user:
      secret: keycloak-admin-secret

  ingress:
    enabled: false

  db:
    vendor: postgres
    host: keycloak-postgres-rw      # CNPG primary servis (read-write)
    database: ${PG_DATABASE}
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password

  hostname:
    hostname: ${KEYCLOAK_HOSTNAME}

  http:
    tlsSecret: keycloak-tls

  # TLS terminira Ingress; Keycloak je iza proxyja.
  proxy:
    headers: xforwarded

  startOptimized: false

  additionalOptions:
    - name: metrics-enabled
      value: "true"
    - name: health-enabled
      value: "true"

  scheduling:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: keycloak
            app.kubernetes.io/managed-by: keycloak-operator
            app.kubernetes.io/component: server

  resources:
    requests:
      cpu: "1000m"
      memory: "1700Mi"
    limits:
      cpu: "2"
      memory: "3Gi"