apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres
  namespace: ${NAMESPACE}
spec:
  instances: ${PG_INSTANCES}

  storage:
    size: ${PG_STORAGE_SIZE}
##STORAGECLASS##

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  bootstrap:
    initdb:
      database: ${PG_DATABASE}
      owner: ${PG_USERNAME}
      secret:
        name: keycloak-db-secret

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"